name: Deploy-headlamp

on:
  push:
    branches:
      - main

jobs:

  helm-validation:
    name: Helm Validation
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Helm Lint
        run: |
          echo "Running Helm lint..."
          helm lint ./argocd-apps

      - name: Helm Template
        run: |
          echo "Rendering Helm template..."
          helm template headlamp-argocd ./argocd-apps \
            -f apps/headlamp-app.yaml \
            --namespace argocd

  deploy:
    name: Deploy-helm-App-of-Apps
    runs-on: self-hosted
    needs: helm-validation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to ArgoCD
        env:
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          echo "Logging in to ArgoCD..."
          argocd login localhost:8080 \
            --username admin \
            --password $ARGOCD_PASSWORD \
            --insecure

      - name: Deploy Helm-based App-of-Apps
        run: |
          echo "Deploying Helm-based App-of-Apps..."
          helm upgrade --install headlamp-argocd ./argocd-apps \
            -n argocd \
            -f apps/headlamp-app.yaml \
            --wait \
            --timeout 600s

      - name: List deployed Helm releases
        run: |
          echo "Listing deployed Helm releases..."
          helm list -n argocd

      - name: Check ArgoCD applications
        run: |
          echo "Checking ArgoCD applications..."
          argocd app list

      - name: Sync App-of-Apps in ArgoCD
        run: |
          echo "Syncing App-of-Apps in ArgoCD..."
          argocd app sync argocd-app-of-apps-headlamp --timeout 600
          argocd app wait argocd-app-of-apps-headlamp --timeout 600
